# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM centos

RUN yum upgrade -y && \
    yum update -y && \
    yum install -y java-1.8.0-openjdk-devel unzip git maven

RUN useradd -m ptestuser
RUN mkdir -p /home/ptestuser
COPY smart-apply-patch.sh copy-test-logs.sh scratch/build.patch /home/ptestuser/scratch/
RUN chown -R ptestuser /home/ptestuser
RUN chmod -R 755 /home/ptestuser
RUN ls -l /home
RUN cat /home/ptestuser/scratch/build.patch
USER ptestuser
RUN cd /home/ptestuser
WORKDIR /home/ptestuser
ARG workingDir
ARG mavenEnvOpts
ARG repository
ARG branch
ARG buildTag

ENV MAVEN_OPTS="$mavenEnvOpts"
RUN /usr/bin/mvn -version
RUN echo $MAVEN_OPTS
RUN /usr/bin/git clone $repository
RUN cd hive

WORKDIR /home/ptestuser/hive
RUN /usr/bin/git checkout $branch || checkout -b $branch origin/$branch &&\
    /usr/bin/git reset --hard origin/$branch &&\
    /usr/bin/git merge --ff-only origin/$branch &&\
    /home/ptestuser/scratch/smart-apply-patch.sh /home/ptestuser/scratch/build.patch &&\
    /usr/bin/mvn -q -B install -Dtest=TestMetastoreConf &&\
    cd itests &&\
    /usr/bin/mvn -q -B install -DskipSparkTests -DskipTests &&\
    echo This build is labeled $buildTag
